### ISSUE TITLE
AF-Android-SDK.jar does not seem to exist in the right place?

### ISSUE THREAD

**Issue by jacquesdev** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#35] opened 2018-04-13 18:19 UTC
I have the following setup (using cordova-plugin-appsflyer-sdk@4.3.0 and also tested with cordova-plugin-appsflyer-sdk@4.4.0):

```
cli packages: (/Users/jacques/dev/mobile/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    Cordova Platforms : android 6.4.0
    Ionic Framework   : ionic1 1.3.5

System:

    ios-deploy : 1.9.2 
    Node       : v8.9.4
    npm        : 2.15.12 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3 Build version 9E145 

Environment Variables:

    ANDROID_HOME : /Library/Android/sdk

```

I get the error below

```
Could not resolve all files for configuration ':debugCompileClasspath'.
> Failed to transform file 'AF-Android-SDK.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file /Users/user/dev/mobile/platforms/android/src/main/libs/AF-Android-SDK.jar does not exist.
```

It looks like main/libs is missing from src/. It does work when I manually copy the SDK.jar file into that location, but for whatever reason it seems it's not being copied over.

**Comment by af-fess** [comment] 2018-05-01 07:52
in latest version we load SDK from maven:

**Comment by Hitman666** [comment] 2018-05-16 07:35
Hey @af-fess,

I tried what you suggested, as well as copying the `AF-Android-SDK.jar` file as @jacquesdev suggested, but am still getting this:

```
Error:Execution failed for task ':compileReleaseJavaWithJavac'.
> Failed to create MD5 hash for file 
'/Users/nikola/DEV/TheApp/platforms/android/src/main/libs/AF-Android-SDK.jar'.
```

I'd appreciate any ideas that you may have in order to resolve this.

Thank you!

**Comment by af-fess** [comment] 2018-05-16 09:33
@Hitman666 right, `4.4.0`+ uses latest Cordova android. But looks weird that gradle linking didnt help you.

**Comment by af-fess** [comment] 2018-06-10 10:03
@jacquesdev Please see this comment: https://github.com/AppsFlyerSDK/cordova-plugin-appsflyer-sdk/commit/f5008de9f0474d0581af3063b10ecfa11528905c

Possible duplicate of #24

**Closed by af-fess** 2018-06-10 10:03 UTC
