### ISSUE TITLE
 Deferred Deep Linking not stable work on ios

### ISSUE THREAD

**Issue by YaroslavG** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#74] opened 2019-07-08 12:36 UTC
Hello, 
I use Appsflyer Direct Deeplink and it works fine but when I try set up Deferred Deep Linking and test it I can see that it unstable work. Specifically, I almost always get variable conversionData.data.is_first_launch - "false", even if I delete the application before.
 Any help?

**Comment by af-vs** [comment] 2019-07-22 09:27
Hi @YaroslavG !

As we have discussed this matter in a Support ticket I will go ahead and close this issue.

For reference to any visitors here, please make sure to have Android Auto-Backup disabled on your device when testing and having your device whitelisted in AppsFlyer.

Thank you!

**Closed by af-vs** 2019-07-22 09:27 UTC

**Comment by codetodya** [comment] 2020-01-23 08:09
is this issue fixed @af-vs

**Comment by af-vs** [comment] 2020-01-23 08:22
@codetodya the issue was caused by Android Auto-Backup keeping the app data between reinstalls which caused our SDK to return is_first_launch=false. 

Please make sure to have Android Auto-Backup disabled on your device when testing and having your device whitelisted in AppsFlyer.

The latest versions of our SDK also come with built-in backup rules, so the issue should not appear. Still, you may get Android Manifest merge errors and may need to add backup rules manually as described here-  https://support.appsflyer.com/hc/en-us/articles/207032126-Android-SDK-integration-for-developers#integration-backup-rules

**Comment by codetodya** [comment] 2020-01-24 16:18
Thanks for the update. @af-vs
