### ISSUE TITLE
Install plugin for Android@6.4.0 .java files not install.

### ISSUE THREAD

**Issue by LokeshPatel** [AppsFlyerSDK/cordova-plugin-appsflyer-sdk#39] opened 2018-06-05 09:03 UTC
Hi,

I've tried to install appsflyer plugin for iOS and Android@6.4.0, iOS work fine but in Android .java files not install in android package file.

Plugin.xml file android target files path change then install properly.

**plugin path :** 

```
 <source-file src="src/android/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java" target-dir="app/src/main/java/com/appsflyer/cordova/plugin" />
 <source-file src="src/android/com/appsflyer/cordova/plugin/AppsFlyerConstants.java" target-dir="app/src/main/java/com/appsflyer/cordova/plugin" />
```       
**After changes path install properly and work fine** 

```
  <source-file src="src/android/com/appsflyer/cordova/plugin/AppsFlyerPlugin.java" target-dir="src/com/appsflyer/cordova/plugin" />
  <source-file src="src/android/com/appsflyer/cordova/plugin/AppsFlyerConstants.java" target-dir="src/com/appsflyer/cordova/plugin" />
```

Thanks,
Lokesh Patel

**Comment by af-fess** [comment] 2018-06-10 10:04
@LokeshPatel  Please see this comment: f5008de

Possible duplicate of #24

**Closed by af-fess** 2018-06-10 10:04 UTC
